### ISSUE TITLE
Conversion stuck at vae_decoder

### ISSUE THREAD

**Issue by loranger** [Zabriskije/SD-to-CoreML#1]
Hello,

I think I have an issue, and I'm not sure SD-roCoreML is responsible, but as I can't figure out why, I start with this script.
I try to convert an simple and old SD model (moDi-v1-pruned.ckpt) but it's slow, very very slow.

I did start at noon and it's now 6pm but it's not done yet. I can't understand or explain, could you help, please ?

<img width="1800" alt="SCR-20230718-pyju" src="https://github.com/Zabriskije/SD-to-CoreML/assets/6014/3731b398-18ed-47df-88cf-2696e3f96564">

I run macOS 13.4.1 on a Macbook pro (Apple M1 Max)

**Comment by Zabriskije** [comment]
A normal conversion for a single implementation shouldn't take more than 30min (it takes around 20min in my MacBook Air M1 8GB). I suggest aborting if it takes longer (<kbd>⌃</kbd>+<kbd>C</kbd>). I've also just tested the script, and it runs fine.

For your specific problem, I can't see any meaningful error message, so I cannot fully understand what could be the issue here. Have you tried starting over?
If so, there's a plentitude of factors involving Miniconda, diffusers, and the `ml-stable-diffusion` environment that makes it hard to debug. I suggest deleting the `ml-stable-diffusion` environment in your Miniconda folder, the `ml-stable-diffusion` repo, and making a fresh install. If that doesn't solve the issue, and since this seems unrelated to the script itself, you can post your logs in the [Mochi Diffusion Discord server](https://discord.gg/x2kartzxGv) for further help.
